export { scanProject, getPageFiles } from './project.js'
export { analyzeSize } from './size.js'
export { analyzeDependency, generateMermaidGraph } from './dependency.js'
export { analyzeUnused } from './unused-code.js'
export { compressImages, type CompressOptions } from './image.js'
